### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Slexom/earth2java#1]
`Minecraft v1.15.2`
`Forge v31.2.5`
`Earth2Java v1.2.0`

My server crashed when it tried to load the game with this mod.
[Crash Report](https://gist.github.com/WenXin20/aea753c8471731e8065056ddc3c6a097)

**Comment by Slexom** [comment]
The bug has been fixed. On a local server it start without giving any error. The new version(1.2.1) will soon be available on the CurseForge page (https://www.curseforge.com/minecraft/mc-mods/earth2java-mobs).
I'll leave this issue open in case you still have problems running the mod on a server.

**Comment by WenXin20** [comment]
Thanks! I'll give it a try tonight or tomorrow.

**Comment by WenXin20** [comment]
Just tried the new version, but my client crashed while trying to join the server.
[Crash Report](https://gist.github.com/WenXin20/dbcd42f6c4e1a9461d8ba1b4f81dd051)

**Comment by Slexom** [comment]
Look like the fluid tag for the mud is still not loaded at the time the game check for it.
Try this, modified 1.2.1 to fix the issue(I hope 🤣 ):
https://e2j.s3.eu-central-1.amazonaws.com/earth2java_mobs_1.2.1%40WenXin.jar
Thank you for the reports 😃

**Comment by katubug** [comment]
Hi, I think I'm having this same issue on my dedicated server. I'm using forge 31.2.30, and Earth2Java 1.3.2.

Here's my crash report: https://pastebin.com/FSzA7rJ3

**Comment by Slexom** [comment]
#3
