### ISSUE TITLE
Crash trying to place a melon lantern on the world

### ISSUE THREAD

**Issue by vico93** [Slexom/earth2java#102]
- Minecraft: 1.19.4
- Fabric Loader 0.14.19-1.19.4
- Fabric API 0.80.0+1.19.4
- Earth2Java 1.9.3

Crash report: [HERE](https://gist.github.com/vico93/53ea4020b9fd6c919f2d106832bd4f86)

**Comment by Slexom** [comment]
@vico93 can you check if this solve the issue?
[earth2java-fabric-1.9.3+1.19.4.zip](https://github.com/Slexom/earth2java/files/11377855/earth2java-fabric-1.9.3%2B1.19.4.zip)

**Comment by vico93** [comment]
@Slexom that build seems to have solved the issue! Thanks!

**Comment by vico93** [comment]
Actually i got this crash randomly in the same world. Can it be related to your mod or another one? [HERE](https://gist.github.com/vico93/d7987a8302fda188fedf6fb913c8f6c0)
