### ISSUE TITLE
Sooty Pig texture on Latest Version of 1.19.4 Fabric is broken

### ISSUE THREAD

**Issue by Autello** [Slexom/earth2java#103]

**Comment by Autello** [comment]
Not sure if my reply to the email I got went to you so here's the link again

https://imgur.com/a/JxAYYnp

**Comment by vico93** [comment]
Maybe is this very same mob? If yes, i'm having the very same problem...
![2023-05-06_17 34 34](https://user-images.githubusercontent.com/3485505/236648122-52885742-82eb-4497-8f1c-425284d86996.png)

**Comment by vico93** [comment]
Can't wait to test this build!
