### ISSUE TITLE
[Crash] World load causes crash due to Pinto Cow, involving Elytra Slot?

### ISSUE THREAD

**Issue by purejosh** [Slexom/earth2java#106]
Hey, got a weird one. I'm seeing in the stacktrace that it's referencing Elytra Slot for the crash, but the crash itself is from rendering an entity, and that entity is the pinto_cow... It's weird. Can you take a look at this, please? 

Fabric 1.19.2 client, single player world, using Earth2Java 1.10.0 and many other mods.

https://gist.github.com/purejosh/07027beda74a07a659f93567c1204a4e

**Comment by Slexom** [comment]
That cow want to explore the sky? That's the only reason I can found for this :D .
I'll give a look at this weird issue asap. If you generate a new world, is there any other entity that eventually crash the game?

**Comment by purejosh** [comment]
Disregard, happening without E2J installed.
