### ISSUE TITLE
 1.10.0b did not fix sooty pig texture as intended

### ISSUE THREAD

**Issue by OmegaDovah** [Slexom/earth2java#107]
Original post 
https://github.com/Slexom/earth2java/issues/105#issuecomment-1569102609_

The update that you release did not fix the issue 
![image](https://user-images.githubusercontent.com/105981820/242827743-39ea0f08-0a43-4069-a770-4a26b1efa1db.png)

**Comment by Slexom** [comment]
1.10.1 as fixed it
