### ISSUE TITLE
Game Freezes when Loading Save UNPLAYABLE

### ISSUE THREAD

**Issue by Camawama** [Slexom/earth2java#11]
**Target Version**
*Mod Loader*: Forge (LATEST)
*Minecraft Version*: 1.16.1
*Mod Version*: Latest

**Describe the bug**
When creating a world, everything works perfectly fine. When I save and exit that world and attempt to get back in, the game stops at 100% and just freezes up entirely. The only way to close the game is task manager. It took me 5 days to figure out which mod was causing the issue and my modpack and I finally pinpointed it to your mod. Hopefully, it can be fixed since I do love your mod

**To Reproduce**
Create a world
Save and Exit
Attempt to join the world

**Expected behavior**
The game should not crash when loading a save file

**Screenshots**
![image](https://user-images.githubusercontent.com/43620900/89218996-9df24d80-d594-11ea-95d7-18650e62a5db.png)

This could be a conflict with another mod, but it would be difficult to find which one is the cause.

**Comment by Slexom** [comment]
Can you provide me the logs(_debug.log_ and/or _latest.log_ in logs folder) and tell me the other mods you have?

**Comment by Camawama** [comment]
I am sad to say that even after removing your mod and enabling the other mods again, the issue persists. It must be a problem with Forge and your Mod was affected by this problem as well as a few others. I am currently looking for the next culprit...

Forge Version: forge-32.0.98
Mods List: https://pastebin.com/u7X8FZGj
Logs:
[latest.log](https://github.com/Slexom/earth2java/files/5018119/latest.log)

Even if it isn't your mod causing the issue, hopefully, we can figure this out. It's been the biggest roadblock in the development of my Modpack. Thank you for your quick response.

**Comment by Camawama** [comment]
The results I am producing seem to be random, which is really making this difficult. It may not have even been your mod at all, rather a mere coincidence. I hope I can figure this out, I am really stressing over this since it's been almost a week and I haven't resolved this issue.

**Comment by Slexom** [comment]
I got similar issues on my matches with Quark, removing it and all load fine. Can you try removing quark and related?
If the issue is the same as mine, the server(there is a server also on single player) goes in timeout, that's why it look stucked. If you as soon as it start loading Alt+Tab to desktop and wait, the game will show you the timeout error. If you try to reload it all goes fine. 
Anyway I'll investigate about it.

**Comment by Camawama** [comment]
I think it actually might have been Cyclic causing the issue! I am going to do a couple more tests and let you know. Thank you for your help :)

**Comment by Slexom** [comment]
Also try to allocate more ram, this could help. Some mods are very heavy on that side.

**Comment by Camawama** [comment]
I don't think it would be a RAM issue, since I have 8gb of RAM allocated! Lol. I have been doing further testing, and I've come to the conclusion that it is NOT your mod. I wanted to ask if I should close this thread or wait until I figure it out so I could help others?

**Comment by Camawama** [comment]
Alright, we're getting places. I have figured out that it's a mod conflicting with BIOME MODS. Something doesn't like Biomes O' Plenty or Oh The Biomes You'll Go. Trying to figure it out!

**Comment by Camawama** [comment]
IT WAS THE MOD "Falling Tree" conflicting with the Biome Mods! Without Falling Tree Installed, I'm able to run worlds perfectly fine and reload them without it soft locking.

**Comment by Camawama** [comment]
https://github.com/RakSrinaNa/FallingTree/issues/16
