### ISSUE TITLE
Question about 1.20.4

### ISSUE THREAD

**Issue by vico93** [Slexom/earth2java#119]
Is an update to 1.20.4 planned? Sorry to ask about that.

**Comment by vlad8599** [comment]
Same question, update please!

**Comment by vico93** [comment]
For further context, similar to #121, i tried to place 1.10.2 for MC 1.20.2 on my 1.20.4 profile, surprisingly the game boots on, config is created, but unfortunately when entering a world and trying to spawn a E2J mob via a spawn egg (natural mob spawing seems to work) crashes the game with this report [HERE](https://gist.github.com/vico93/9d18aaca624acdeedf57c662da88681c).

I suspect its a minor mixin correction, but maybe i'm wrong.

**Comment by vico93** [comment]
![image](https://github.com/Slexom/earth2java/assets/3485505/a60231bb-a020-4cec-b7eb-e11b0504f6de)
