### ISSUE TITLE
Bug with biome names in config

### ISSUE THREAD

**Issue by calloatti** [Slexom/earth2java#12]
**Target Version**
*Mod Loader*: Fabric 0.9.0+204
*Minecraft Version*:  1.16.1
*Mod Version*: Earth2Java-1.1.0+1.16.1.jar

**Describe the bug**

![2020-08-04_00 56 39](https://user-images.githubusercontent.com/12817862/89251540-ab87f180-d5ed-11ea-9e27-2042be377df5.png)

**To Reproduce**
Open the mod config using modmenu

**Expected behavior**
Readable biome names

**Screenshots**

**Mod List**
Add here any other mod you are using together with Earth2Java.

**Logs**
Drop here the log.

**Comment by Slexom** [comment]
Is a cloth config bug, string s are mot correctly aligned (https://github.com/shedaniel/cloth-config/issues/54#issue-667425808) . Click on a row move the cursor to the beginning and the full string pop out.
