### ISSUE TITLE
Earth2Java Chickens take Fall Damage 1.20.1

### ISSUE THREAD

**Issue by Pyrotrainthing** [Slexom/earth2java#122]
The Earth2Java chickens take fall damage, I doubt that's intentional. I recorded a video of the issue but sadly Github doesn't support files bigger than 10 Megabytes.
I am using the Forge 1.20.1 version if it makes any difference.

**Comment by Slexom** [comment]
This ha been fixed in 1.11.0 for mc 1.21.
Will be back ported to MC 1.20.1.
