### ISSUE TITLE
muddy pig loses his mud 😭

### ISSUE THREAD

**Issue by DanU-coder** [Slexom/earth2java#124]
https://github.com/Slexom/earth2java/assets/128765128/a54be3a7-0983-4691-b882-0b481dc060da
When a pig rolls in the mud, its texture changes, but the moment it gets out of there it returns to its dry state.

**Comment by Slexom** [comment]
This ha been fixed in 1.11.0 for mc 1.21.
Will be back ported to MC 1.20.1.
