### ISSUE TITLE
Crash in Fabric 1.21

### ISSUE THREAD

**Issue by vico93** [Slexom/earth2java#128]
Just installed 1.11.0 on my modpack, but when i tried to boot the game i got [this crash](https://gist.github.com/vico93/513d1969c982d9191e0ef6e1087b1286).

**Comment by Slexom** [comment]
can you provide me the pack?

**Comment by flippnfadoodle** [comment]
Hi,

I am getting the same error it seems, here is the error log:
https://gist.github.com/flippnfadoodle/d5a43a6859ce7c7f1b705b53f4a047e9

Here is a download link to my modpack with all of the mods hosted on the server:
https://www.mediafire.com/file/94ayp1jmos7p670/SERVERMods.zip/file

**Comment by Slexom** [comment]
> Hi,
> 
> I am getting the same error it seems, here is the error log: https://gist.github.com/flippnfadoodle/d5a43a6859ce7c7f1b705b53f4a047e9
> 
> Here is a download link to my modpack with all of the mods hosted on the server: https://www.mediafire.com/file/94ayp1jmos7p670/SERVERMods.zip/file

I'm having any mod in that pack giving errors with mixins... what's going on? XD
The method related to the crash is there, without anything else the mod run fine both client and server side...

**Comment by flippnfadoodle** [comment]
I am running a few data packs on my world too, would that have any effect?

**Comment by vico93** [comment]
> can you provide me the pack?

Sure. Do you have Discord? I can zip it and send the link to you on there.

**Comment by flippnfadoodle** [comment]
Yep, my username is the same as here: flippnfadoodle

**Comment by Slexom** [comment]
Is a problem with architectury or loom in general, is injecting the refMap file with the wrong name. I'm going to manually fix it  with the correct name

**Comment by flippnfadoodle** [comment]
Awesome, thank you!

**Comment by vico93** [comment]
> Yep, my username is the same as here: flippnfadoodle

oh i meant for @Slexom rs. But i'm glad the issue was identified
