### ISSUE TITLE
1.16.2 GenerationSettingsAccessor mixin & mod compatibility

### ISSUE THREAD

**Issue by Katorone** [Slexom/earth2java#13]
**Target Version**
*Mod Loader*: fabric@0.18.0+build.397-1.16
*Minecraft Version*:  1.16.2
*Mod Version*: earthtojavamobs@1.2.0+1.16.2

**Describe the bug**
`Method overwrite conflict for setFeatures in appliedenergistics2.mixins.json:structure.GenerationSettingsAccessor, previously written by slexom.earthtojava.mobs.mixins.MixinGenerationSettings. Skipping method.`

Two mods are trying to overwrite the same method, causing incompatibility.  I'm reporting this to the AE2 team as well.

**To Reproduce**
Install earth2java and AE2 for Fabric 1.16.2

**Expected behavior**
Mod compatibility

**Mod List**
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3033292

**Comment by shartte** [comment]
Regarding https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4600

Please don't add methods to a class without using your mod-id as a prefix in the method-name, unless you are using an accessor.
For accessing this class's private field, you can just copy paste the Accessor we use:

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fabric/master/src/main/java/appeng/mixins/structure/GenerationSettingsAccessor.java

**Comment by Slexom** [comment]
This is an issue that come from the lack of an unified api for biomes in fabric 1.16.2. Those mods, and others too, use same approach to do same things and this generate errors and incompatibility. This isn't the only combination of mods that generate this, or related, issues.
I'll disable any feature that regard generations until we have an api.

**Comment by shartte** [comment]
@Slexom Just copy paste our Accessor Mixin, it does the same thing and any number of mods can use the exact same one without causing incompatibility.

**Comment by Slexom** [comment]
I'll look at it, thank you.

**Comment by shartte** [comment]
p.s.: If you want an alternative: If you prefix the methods you add with your mod-id, (earth2java_getXYZ), that will also be okay.

**Comment by Slexom** [comment]
Thank you for the tips @shartte

**Comment by Katorone** [comment]
Thank you!
