### ISSUE TITLE
Mobs Not Dropping Anything :/

### ISSUE THREAD

**Issue by NoahDaNugget** [Slexom/earth2java#130]
Loaded into the newest version of minecraft with this mod and noticed all mob drops are working/functioning besides all the earth2java mobs. I have all necessities installed. If I could get some insight I would appreciate it :)

**Comment by Slexom** [comment]
I've recently released an update, 1.11.3, that should fix this issue.

**Comment by NoahDaNugget** [comment]
Thank You!
