### ISSUE TITLE
Earth2Java cows are spawning in water only

### ISSUE THREAD

**Issue by vico93** [Slexom/earth2java#132]
![2024-07-12_15 38 53](https://github.com/user-attachments/assets/37350a21-ca2b-4fa4-b704-637889650db1)

**Comment by Slexom** [comment]
I'll fix it asap... Don't know why or how spawn tags for sunset cow and tropical slime are switched...

**Comment by vico93** [comment]
I also saw a couple of rainbow sheep on similar situation... will test the freshly uploaded version to see if still happens with other mod's mobs.
