### ISSUE TITLE
game crashes while loading fancy chicken model.

### ISSUE THREAD

**Issue by Voidpossums** [Slexom/earth2java#135]
like the title says, my game crashes whenever it tries to load the fancy chicken model. i have attatched a screenshot of the text the game gave when it crashed.
![Schermafbeelding 2024-07-13 103840](https://github.com/user-attachments/assets/44afcb22-5a80-4b8b-8582-ab2dce349537)

**Comment by Slexom** [comment]
As been already fixed, waiting on curseforge to publish new version
