### ISSUE TITLE
Earth2Java Unnexpected Crash from 4 mods.

### ISSUE THREAD

**Issue by makumaku1974** [Slexom/earth2java#136]
Recently I was testing a list of mods, but this 4 mods that I added crashed with it.
![image](https://github.com/user-attachments/assets/814f2bb4-f0dd-4475-ac2b-06a6f08752fc)

The reason why it crashed due to rendering issues with the Fancy Chicken.
Here is the crash report: https://mclo.gs/cF0h1kp
Here is the log: https://mclo.gs/KuvutND

**Comment by Slexom** [comment]
Download latest version from curseforge.
https://www.curseforge.com/minecraft/mc-mods/earth2java/files/5528071

**Comment by makumaku1974** [comment]
Thank you! Could I also add your mod to my modpack, with credit ofc.

**Comment by makumaku1974** [comment]
> Download latest version from curseforge. https://www.curseforge.com/minecraft/mc-mods/earth2java/files/5528071

Still crashed with the latest version... 1.11.5 from modrinth.

I'll check the other mods since it looks like it isnt this mod's problem.
