### ISSUE TITLE
wrong biome name for pinkFootedPig in default config

### ISSUE THREAD

**Issue by calloatti** [Slexom/earth2java#15]
**Target Version**
*Mod Loader*: Fabric 
*Minecraft Version*:  1.16.1
*Mod Version*: Earth2Java-1.1.0+1.16.1.jar

**Describe the bug**
config is wrong for   "pinkFootedPig"

**To Reproduce**
open default config:

```
  "pinkFootedPig": {
    "weight": 10,
    "groupMin": 2,
    "groupMax": 4,
    "spawnBiomes": [
      "plains"
    ]
```

**Expected behavior**

 ```
 "pinkFootedPig": {
    "weight": 10,
    "groupMin": 2,
    "groupMax": 4,
    "spawnBiomes": [
      "minecraft:plains"
    ]

```

**Comment by Slexom** [comment]
Is the biome category. Read here https://github.com/Slexom/earth2java/wiki/Entity-spawn-configuration#fabric

**Comment by calloatti** [comment]
oh ok

**Comment by calloatti** [comment]
One question the Fabric "**Biome Category" is just checking if the category string is part of the biome name?**
