### ISSUE TITLE
1.16.1 - spawnBiomes values get reset at game launch for all mobs

### ISSUE THREAD

**Issue by bessiq** [Slexom/earth2java#2]
Forge: 32.0.38

Hi,

Whenever I add or remove biomes in earthtojavamobs-common.toml, they always get reset back to the original values when I launch Minecraft. The weights and group sizes I've changed don't reset though. Coincidentally, I had the same issue with a similar mod called Earths Animals, but other mods that have biome spawn settings seem to be fine.

Thanks for any help you can provide. Love the creatures in this mod.

**Comment by Slexom** [comment]
Released a new version right now, that fix that issue. Please test it and report if the bug is still present for you.
https://www.curseforge.com/minecraft/mc-mods/earth2java-mobs/download/2994657

**Comment by bessiq** [comment]
I can confirm the config is not resetting anymore, and I don't see the mobs in biomes I've removed them from. Thanks for the fix!
