### ISSUE TITLE
Animals not respecting spawn rules

### ISSUE THREAD

**Issue by shouxd** [Slexom/earth2java#22]
Last fabric version, Minecraft 1.16.3, Last Earthtojava version.

Mobs do not respect spawn weights nor spawn biomes thus there is no point in trying to get them to spawn in modded biomes as they cant be controlled via config file anyway.

**Comment by Artheow** [comment]
This issue is still happening using 1.16.3 or 1.16.4 version of the mod with latest fabric api/loader.Setting biome category as stated in the wiki do not make new mobs spawn in any modded biome.

**Comment by Artheow** [comment]
Hi, seems like this isn't resolve, atleast for my usage so i suspect problems could be on my end.What i've been trying to do is setting  spawn categories in the config (like plains for albino cow) but the only mob that do spawn in modded plains is the pink footed pink which is already set to spawn in the plains category by default.

**Comment by shouxd** [comment]
Yeah the problem still happens in the latest release: I tried to restrict glowsquids only to deep oceans and they still spawned everywhere in the world. Tried to set glowsquid spawn weight to 0 and they still appeared.

**Comment by Slexom** [comment]
@shouxd @Artheow Can you please paste your configuration here?

**Comment by shouxd** [comment]
Sure! Mine is this one: https://pastebin.com/FtYuZBKC

**Comment by Artheow** [comment]
Here's mine, sorry for the delay: https://pastebin.com/xjqQDaY6

**Comment by Artheow** [comment]
hi sorry for the delay , here's mine (tried with caps, only biome categories): 
https://pastebin.com/xjqQDaY6

**Comment by PandaBearJelly** [comment]
Just going to add that I have also been having spawn issues. I was trying to get the mobs to spawn in BYG biomes but the config seems to be completely ignored (also couldn't get them to not spawn in vanilla biomes while I was experimenting.)

I was trying a lot of things so this may be a bit funky: https://pastebin.com/e13ZxfsW
