### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by Slexom** [Slexom/earth2java#3]
Hi, I think I'm having this same issue on my dedicated server. I'm using forge 31.2.30, and Earth2Java 1.3.2.

Here's my crash report: https://pastebin.com/FSzA7rJ3

_Originally posted by @katubug in https://github.com/Slexom/earth2java/issues/1#issuecomment-655797565_

**Comment by Slexom** [comment]
Downlaod the following version and let me know if the problem is solved:
https://e2j.s3.eu-central-1.amazonaws.com/earth2java_1.3.2_forge_1.15.2+__%40katubug.jar

**Comment by katubug** [comment]
Thanks for your response! I'll test it out tomorrow and let you know!
