### ISSUE TITLE
Massive pigs spawn

### ISSUE THREAD

**Issue by Slexom** [Slexom/earth2java#6]
There is a evry low chance that a large amount of pigs spawn on certain biomes.

**Known Biomes**

- Plains

**Comment by bessiq** [comment]
Noticed this too, but didn't realize it was related to this mod. I sometimes see a lot of vanilla pigs in the Snowy Tundra biome, but I have changed a lot of the default biomes for mob spawns from this mod. I do have the Snowy Tundra as a spawn biome for Pale Pigs, if that is helpful.
