### ISSUE TITLE
Mobs not spawning in Terralith biomes

### ISSUE THREAD

**Issue by Muffintiem** [Slexom/earth2java#62]
I added some biomes from Terralith to the spawning parameters in the config file but for some reason they still don't spawn.

**Comment by Slexom** [comment]
Which version for which Minecraft? Paste also your current configuration

**Comment by Muffintiem** [comment]
Oh yeah I forgot! It's version I.7.4 for 1.18. I added the biomes using the Mod Menu, making sure to close and reload the game. I also added the Mooblooms to Meadows since I felt they fit there too and I did find them in Meadows so I know they are at least being added in vanilla biomes.

**Comment by cygnusharvey** [comment]
I think that has to do with Terralith, it happened for me with Mythic Mounts. Some spawned, some didn't.

**Comment by Muffintiem** [comment]
Oh it's happening with Mythic Mounts too? I'm sure it's something to do with Terralith too but it seems other mods have been able to make it work.

**Comment by Razatop** [comment]
Having this issue myself as well, think it's because of the way Terralith is handling biome tags?

Earth2Java-1.8.0+1.18.2.jar
Terralith_v2.2.1a.jar
fabric-api.0.48.0.jar

Can drop more info if needed.
