### ISSUE TITLE
Mud generating even when disabled in config

### ISSUE THREAD

**Issue by mj717** [Slexom/earth2java#71]
I am having an issue with mud lakes generating even when I disable them in the config.

I am playing on 18.1 with the latest release of this mod. I tried setting the frequency of the lakes to zero in addition to disabling them, but this caused the game to [crash](https://jpst.it/2KMUW). I have the last log [here](https://jpst.it/2KMVr), but there's not much in it, I don't think. Thanks for this great mod!

**Comment by BrekiTomasson** [comment]
Problem remains in 1.18.2.
