### ISSUE TITLE
Game crashed when I attacked a horned sheep

### ISSUE THREAD

**Issue by linzexin022** [Slexom/earth2java#8]
Hi there, I was testing your mod but it crashed when I attacked the horned sheep. Here's the game log:
[latest.log](https://github.com/Slexom/earth2java/files/4992503/latest.log)

**Comment by Slexom** [comment]
A missing _GENERIC_ATTACK_DAMAGE_ attribute cause that issue.
The bug has been corrected and the fix will be released on the next update.
