### ISSUE TITLE
Flowing mud is missing its texture

### ISSUE THREAD

**Issue by inflorescence91838** [Slexom/earth2java#81]
Flowing mud has the typical checkboard pattern, which means its texture is somehow missing. Only mod installed is Earth2Java and its dependencies.

![2022-07-05_23 37 07](https://user-images.githubusercontent.com/105180467/177470204-d75301a0-03cf-4336-9883-12690dc58ec9.png)

**Comment by Slexom** [comment]
A new version as been released fixing those bugs. Thank you for your report.
