### ISSUE TITLE
[CRASH] Tropical slimes are crashing client when rendered

### ISSUE THREAD

**Issue by purejosh** [Slexom/earth2java#82]
1.18.2, when a tropical slime is rendered, it crashes the client.
[2022-07-11-7.log](https://github.com/Slexom/earth2java/files/9085334/2022-07-11-7.log)

**Comment by purejosh** [comment]
@Slexom Any updates on this crash? This is pretty severe, and I have to disable slimes to stop my server from crashing.

**Comment by purejosh** [comment]
It's been nearly a month since I've reported this. Please maintain this mod. It's far too incredible to be forgotten.

**Comment by Slexom** [comment]
1.18.2 Is not maintained

**Comment by purejosh** [comment]
It was maintained when I posted this github, right? Is this bug fixed in the newer versions?
