### ISSUE TITLE
Mud texture is black.

### ISSUE THREAD

**Issue by johannesspinnenschreck** [Slexom/earth2java#9]
**Target Version**
*Mod Loader*: Forge
*Minecraft Version*:  1.16.1
*Mod Version*: 2.2.0

**Describe the bug**
The texture of mud appears to be black, despite being brown within the .jar file.

**To Reproduce**
Place down mud with a mud bucket, or find a mud pool in the world

**Expected behavior**
I think the mud is supposed to be brown.

**Screenshots**
![2020-08-01_22 16 10](https://user-images.githubusercontent.com/69090516/89109782-a6d40980-d444-11ea-823b-a448771d6743.png)

**Comment by Slexom** [comment]
Are you using optifine?

**Comment by johannesspinnenschreck** [comment]
Yes I am.

**Comment by Slexom** [comment]
Bingo! 
I'm already looking for a solution for it.

**Comment by johannesspinnenschreck** [comment]
One thing I forgot to mention is that the forge version is missing the mud bucket texture, the reason why it's there  in the screenshot is because I added it.
