### ISSUE TITLE
Biome Categorys not working in 1.18.2

### ISSUE THREAD

**Issue by Kippu26** [Slexom/earth2java#95]
The Biome Categories don't work in the 1.18.2 version of this mod. Entities only spawn when you add minecraft: to the biomes in the config which makes the mod not compatible with biome mods.

**Comment by Razatop** [comment]
Yup, this is an issue he said he wouldn't fix for 1.18.2 and it's only going to be fixed for 1.19+ IIRC

Yup: https://github.com/Slexom/earth2java/issues/62
